Support for starting multiple instances via init script

diff --git a/src/deb/init.d/elasticsearch b/src/deb/init.d/elasticsearch
--- a/src/deb/init.d/elasticsearch
+++ b/src/deb/init.d/elasticsearch
@@ -90,6 +90,7 @@ CONF_DIR=/etc/$NAME
 # ElasticSearch configuration file (elasticsearch.yml)
 CONF_FILE=$CONF_DIR/elasticsearch.yml
 
+NUM_INSTANCES=2
 # End of variables that can be overwritten in $DEFAULT
 
 # overwrite settings from default file
@@ -97,10 +98,17 @@ if [ -f "$DEFAULT" ]; then
 	. "$DEFAULT"
 fi
 
+getPidFile() {
+  if [ -z $1 ] || [ "$1" = "1" ] ; then
+    echo "/var/run/$NAME.pid"
+  else
+    echo "/var/run/$NAME-$1.pid"
+  fi
+}
+
 # Define other required variables
-PID_FILE=/var/run/$NAME.pid
 DAEMON=$ES_HOME/bin/elasticsearch
-DAEMON_OPTS="-p $PID_FILE -Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR"
+DAEMON_OPTS="-Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR"
 
 export ES_HEAP_SIZE
 export ES_HEAP_NEWSIZE
@@ -132,19 +140,9 @@ case "$1" in
 		exit 1
 	fi
 
-	log_daemon_msg "Starting $DESC"
-
-	pid=`pidofproc -p $PID_FILE elasticsearch`
-	if [ -n "$pid" ] ; then
-		log_begin_msg "Already running."
-		log_end_msg 0
-		exit 0
-	fi
-
 	# Prepare environment
 	mkdir -p "$LOG_DIR" "$DATA_DIR" "$WORK_DIR" && chown "$ES_USER":"$ES_GROUP" "$LOG_DIR" "$DATA_DIR" "$WORK_DIR"
-	touch "$PID_FILE" && chown "$ES_USER":"$ES_GROUP" "$PID_FILE"
-
+	
 	if [ -n "$MAX_OPEN_FILES" ]; then
 		ulimit -n $MAX_OPEN_FILES
 	fi
@@ -152,39 +150,63 @@ case "$1" in
 	if [ -n "$MAX_LOCKED_MEMORY" ]; then
 		ulimit -l $MAX_LOCKED_MEMORY
 	fi
+	
+	log_daemon_msg "Starting $DESC ($NUM_INSTANCES instances)"
 
-	# Start Daemon
-	start-stop-daemon --start -b --user "$ES_USER" -c "$ES_USER" --pidfile "$PID_FILE" --exec $DAEMON -- $DAEMON_OPTS
+	set -x
+
+	for numInstance in `seq $NUM_INSTANCES` ; do
+
+		PID_FILE=`getPidFile $numInstance`
+		pid=`pidofproc -p $PID_FILE elasticsearch`
+		if [ -n "$pid" ] ; then
+			log_begin_msg "Already running."
+			log_end_msg 0
+			exit 0
+		fi
+
+		touch "$PID_FILE" && chown "$ES_USER":"$ES_GROUP" "$PID_FILE"
+
+		# Start Daemon
+		TMP_DAEMON_OPTS="-p $PID_FILE $DAEMON_OPTS "
+		start-stop-daemon --start -b --user "$ES_USER" -c "$ES_USER" --pidfile "$PID_FILE" --exec $DAEMON -- $TMP_DAEMON_OPTS
+	done
 	log_end_msg $?
 	;;		
   stop)
-	log_daemon_msg "Stopping $DESC"
+	log_daemon_msg "Stopping $DESC ($NUM_INSTANCES instances)"
 
-	if [ -f "$PID_FILE" ]; then 
-		start-stop-daemon --stop --pidfile "$PID_FILE" \
-			--user "$ES_USER" \
-			--retry=TERM/20/KILL/5 >/dev/null
-		if [ $? -eq 1 ]; then
-			log_progress_msg "$DESC is not running but pid file exists, cleaning up"
-		elif [ $? -eq 3 ]; then
-			PID="`cat $PID_FILE`"
-			log_failure_msg "Failed to stop $DESC (pid $PID)"
-			exit 1
+	for numInstance in `seq $NUM_INSTANCES` ; do
+		PID_FILE=`getPidFile $numInstance`
+		if [ -f "$PID_FILE" ]; then 
+			start-stop-daemon --stop --pidfile "$PID_FILE" \
+				--user "$ES_USER" \
+				--retry=TERM/20/KILL/5 >/dev/null
+			if [ $? -eq 1 ]; then
+				log_progress_msg "$DESC is not running but pid file exists, cleaning up"
+			elif [ $? -eq 3 ]; then
+				PID="`cat $PID_FILE`"
+				log_failure_msg "Failed to stop $DESC (pid $PID)"
+				exit 1
+			fi
+			rm -f "$PID_FILE"
+		else
+			log_progress_msg "(not running)"
 		fi
-		rm -f "$PID_FILE"
-	else
-		log_progress_msg "(not running)"
-	fi
+	done
 	log_end_msg 0
 	;;
   status)
-	status_of_proc -p $PID_FILE elasticsearch elasticsearch && exit 0 || exit $?
+	log_daemon_msg "Checking status: $DESC ($NUM_INSTANCES instances)"
+	for numInstance in `seq $NUM_INSTANCES` ; do
+		PID_FILE=`getPidFile $numInstance`
+		status_of_proc -p $PID_FILE elasticsearch elasticsearch || exit $?
+	done
+	exit 0
     ;;
   restart|force-reload)
-	if [ -f "$PID_FILE" ]; then
-		$0 stop
-		sleep 1
-	fi
+	$0 stop
+	sleep 1
 	$0 start
 	;;
   *)
